services:
  postgres:
    volumes:
      - /data/postgres:/var/lib/postgresql/data

  frontend:
    volumes: []
    environment:
      - NODE_ENV=production

  backend:
    volumes:
      - maven-cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=prod
