server {
	# this is auth specific route for next-auth to work for frontend
	location /api/auth/ {
		proxy_pass http://frontend:3000;
	}
	#frontend
	location / {
		proxy_pass http://frontend:3000;
	}
	#backend
	location /api/ {
		proxy_pass http://backend:8080;
	}
}
