spring.application.name=backend

# PostgreSQL 
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Request logging (dev only)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# application.properties
stripe.secret.key=${STRIPE_SECRET_KEY}

# Aws sdk configuration
aws.region=${AWS_DEFAULT_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}

# root user configurations
# app.admin.name=${ADMIN_PASSWORD}
app.admin.password=${ADMIN_PASSWORD}
app.admin.email=${ADMIN_EMAIL}
app.admin.phone=${ADMIN_PHONE}

# email Resend keys
resend.api_key=${RESEND_API_KEY}
resend.email_from=${RESEND_API_KEY}
resend.webhook_secret=${RESEND_WEBHOOK_SECRET}

shippo.token=${SHIPPO_TOKEN}

environment.url=${ENVIRONMENT_URL}
environment.staging=${ENVIRONMENT_STAGING}
