spring.application.name=backend

# logging configuration
server.error.include-stacktrace=never
server.error.include-message=never

# Request logging (dev only)
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# love it so far excludes these external libraries from populating the garbage into the stack trace. still reports important to me information. 
logging.exception-conversion-word=%wEx{full, org.springframework, org.apache.catalina, org.apache.coyote, org.apache.tomcat, jakarta.servlet, java.base, java.lang.reflect}

# PostgreSQL 
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# application.properties
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Aws sdk configuration
aws.region=${AWS_DEFAULT_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}

# root user configurations
# app.admin.name=${ADMIN_PASSWORD}
app.admin.password=${ADMIN_PASSWORD}
app.admin.email=${ADMIN_EMAIL}
app.admin.phone=${ADMIN_PHONE}

# email Resend keys
resend.api_key=${RESEND_API_KEY}
resend.email_from=${RESEND_EMAIL_FROM}
resend.webhook_secret=${RESEND_WEBHOOK_SECRET}

shippo.token=${SHIPPO_TOKEN}

# environment.url=${ENVIRONMENT_URL}
# environment.staging=${ENVIRONMENT_STAGING}
