- hosts: app
  become: true
  tasks:
    - name: install packages
      apt:
        name:
          - git
          - openssh-server
          - curl
          - vim
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: copy public key
      authorized_key:
        user: root
        key: "{{ lookup('env', 'SSH_PUBLIC_KEY') }}"
        state: present

    - name: clone repo
      git:
        repo: https://github.com/ewanchukwilliam/Printer-Marketplace.git
        dest: /app
        version: main

    - name: install lazydocker
      shell: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_via_script.sh | bash
      args: 
        creates: /usr/local/bin/lazydocker
